### ISSUE TITLE
Open Fire and Rescue panel

### ISSUE THREAD

**Issue by doubravap** [CitiesSkylinesModding/CS2-CustomAssetPack#5]
When opening the panel with the "Mio Road assets pack", the "Fire and Rescue Panel Info" will always open at the same time and the entire image will be grayed out until this info panel is closed. 
Game version 1.1.7f1 - Czech localization.

**Comment by kosch104** [comment]
> When opening the panel with the "Mio Road assets pack", the "Fire and Rescue Panel Info" will always open at the same time and the entire image will be grayed out until this info panel is closed. Game version 1.1.7f1 - Czech localization.

That's a known issue and has been reported in APM. Also the road asset pack hasn't been made with this template and would be responsibility of the respective mod author. Unfortunately, the author of this asset pack has retired from modding.
